app:
  volumes:
    - ./:/var/www/bunny/
  build: ./
  environment:
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: super-secret
    DATABASE_HOST: db
    S3_BUCKET: "${S3_BUCKET}"
    S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
    S3_SECRET: "${S3_SECRET}"
    REDIS_URL: redis://redis:6379
  links:
    - redis
    - db
  ports:
    - '5000:5000'
  command: foreman start
redis:
  image: redis
  ports:
    - '6379:6379'
db:
  image: mysql:5.7
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: super-secret
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./.mysql:/var/lib/mysql
